steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/playing-cards-project/train', '-f', 'dockerfiles/train.dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/playing-cards-project/train']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'playing-cards-service'
  - '--image'
  - 'gcr.io/playing-cards-project/train'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'

images:
- gcr.io/playing-cards-project/train
