# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-4
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/playing-cards-project/train:latest
        command:
            - python3
            - src/playing_cards/train.py
        args: []
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: KAGGLE_API_KEY
          value: $KAGGLE_API_KEY
        - name: KAGGLE_API_USERNAME
          value: $KAGGLE_API_USERNAME
        
