program: src/playing_cards/train.py
name: trainingsweep
project: playing_cards  # change this
#entity: ozkanyamaner  # change this
method: random
metric:
  goal: maximize
  name: valid_accuracy
parameters:
  batch_size:
    values: [8, 16, 32, 64]
  epochs:
    value: 5
  lr:
    max: 0.1
    min: 0.0001
  model:
    values: ["CNN", "TimmResNet", "HuggingfaceResnet"]
  seed:
    value: 42
run_cap: 5

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}