steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < configs/config_gpu.yaml > configs/config_gpu.yaml.tmp
      mv configs/config_gpu.yaml.tmp configs/config_gpu.yaml
  secretEnv: ['WANDB_API_KEY', 'KAGGLE_API_KEY', 'KAGGLE_API_USERNAME']

# - name: 'alpine'
#   id: "Show config"
#   waitFor: ['Replace values in the training config']
#   entrypoint: "sh"
#   args:
#     - '-c'
#     - |
#       configs/config_gpu.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west4',
    '--display-name',
    'experiment2',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/config_gpu.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/474989323251/secrets/WANDB_API_KEY/versions/1
    env: 'WANDB_API_KEY'
  - versionName: projects/474989323251/secrets/KAGGLE_API_KEY/versions/1
    env: 'KAGGLE_API_KEY'
  - versionName: projects/474989323251/secrets/KAGGLE_API_USERNAME/versions/1
    env: 'KAGGLE_API_USERNAME'

workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/playing-cards-project/train:latest
      command:
        - python3
        - src/playing_cards/train.py
      args: []